In [2]:
import pandas as pd

In [4]:
pd.DataFrame({"User 1" : ["pretty good", "average"], "User 2": ["Excellent", "Could've beene better"]},
             index=["drink 1", "drink 2"])

              User 1                 User 2
drink 1  pretty good              Excellent
drink 2      average  Could've beene better

In [5]:
pd.Series([1,1,0,1],index=["04-01","04-02","04-03","04-04"],name="Student A")

04-01    1
04-02    1
04-03    0
04-04    1
Name: Student A, dtype: int64

In [6]:
pd.DataFrame({"Apples":[100, 75], "Bananas":[80, 40]}, index=["2023 Sales", "2024 Sales"])

            Apples  Bananas
2023 Sales     100       80
2024 Sales      75       40

In [7]:
pd.Series(["2","1","1"],index=["Eggs","Bacon","cheese"],name="Ingredients")

Eggs      2
Bacon     1
cheese    1
Name: Ingredients, dtype: object

In [8]:
reviews = pd.read_csv("./winemag-data_first150k.csv", index_col=0)

In [9]:
reviews

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder